baseURL = "https://0xdarkz.com/"
languageCode = "es-419"
title = "0xdarkz"
theme = "starfield"
paginate = 9
enableRobotsTXT = true
enableEmoji = true

[params]
  author   = "StaryDarkz"
  description = "Investigaciones de ciberseguridad, threat hunting, cyber threat intelligence, automatización y otras curiosidades"
  avatar   = "/images/avatar.jpg"
  bio      = "Investigaciones de ciberseguridad, threat hunting, cyber threat intelligence, automatización y otras curiosidades."
  linkedin = "https://www.linkedin.com/in/enddyfigueroa/"
  telegram = "https://t.me/StaryDarkz"
  github   = "https://github.com/StaryDarkz"
  thm_url  = "https://tryhackme.com/p/StaryDarkz"
  ld_url   = "https://app.letsdefend.io/user/profile/StaryDarkz"
  googleAnalytics = "G-0H33890XRQ"

[menu]
  [[menu.main]]
    name   = "Inicio"
    url    = "/"
    weight = 1
  [[menu.main]]
    name   = "Blog"
    url    = "/posts/"
    weight = 2
  [[menu.main]]
    name   = "Proyectos"
    url    = "/proyectos/"
    weight = 3
  [[menu.main]]
    name   = "Sobre mí"
    url    = "/about/"
    weight = 4

[taxonomies]
  tag      = "tags"
  category = "categories"

[markup]
  [markup.highlight]
    style              = "monokai"
    lineNos            = true
    lineNumbersInTable = false
    tabWidth           = 2
  [markup.goldmark.renderer]
    unsafe = true

[outputs]
  home    = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]